Repository hamsik22/NBC_W8-9-QuickKick, pull requests merged in 2024-12, with the labels that each got.

#8 [TabBar] 커스텀 탭 바 생성 - Crois
  Quick-Kick.xcodeproj/project.pbxproj
  Quick-Kick/TabBar/Controller/MainTabBarController.swift
  Quick-Kick/TabBar/Model/TabBarDelegate.swift
  Quick-Kick/TabBar/View/MainTabBar.swift
  Quick-Kick/TabBar/View/TabBarItem.swift
Labels: enhancement

#9 feat: 킥보드 등록 화면 UI 구현
  Quick-Kick/AddKickboard/AddKickboardView.swift
  Quick-Kick/AddKickboard/AddKickboardViewController.swift
  Quick-Kick/AddKickboard/MapView.swift
  Quick-Kick/AddKickboard/NoticeView.swift
  Quick-Kick/AppDelegate.swift
  Quick-Kick/Assets.xcassets/mapPicker.imageset/Contents.json
  Quick-Kick/Assets.xcassets/mapPicker.imageset/Image.png
Labels: enhancement

#14 feat: 킥보드 찾기 화면 구현
  Quick-Kick.xcodeproj/project.pbxproj
  Quick-Kick/AppDelegate.swift
  Quick-Kick/Assets.xcassets/LocationResetButtonIcon.imageset/Contents.json
  Quick-Kick/Assets.xcassets/LocationResetButtonIcon.imageset/LocationResetButtonIcon.png
  Quick-Kick/Assets.xcassets/SearchIcon.imageset/Contents.json
  Quick-Kick/Assets.xcassets/SearchIcon.imageset/SearchIcon.png
  Quick-Kick/SearchKickboard/Controller/SearchKickboardViewController.swift
  Quick-Kick/SearchKickboard/View/SearchKickboardMapView.swift
  Quick-Kick/SearchKickboard/View/SearchKickboardView.swift
  Quick-Kick/SearchKickboard/View/SearchLocationBarView.swift
Labels: enhancement

#18 [HotFix] 사용자 위치 권한 요청 추가
  Quick-Kick/Info.plist
  Quick-Kick/SearchKickboard/View/SearchKickboardMapView.swift
Labels: bug

#19 add: Login&SignUpView UI
  Quick-Kick/Assets.xcassets/AppLogo_PurpleBG.imageset/AppLogo_PurpleBG.png
  Quick-Kick/Assets.xcassets/AppLogo_PurpleBG.imageset/Contents.json
  Quick-Kick/Assets.xcassets/AppLogo_WhiteBG.imageset/AppLogo_WhiteBG.png
  Quick-Kick/Assets.xcassets/AppLogo_WhiteBG.imageset/Contents.json
  Quick-Kick/View/LoginView.swift
  Quick-Kick/View/SignUpView.swift
  Quick-Kick/ViewContorller/LoginViewController.swift
  Quick-Kick/ViewContorller/SignUpViewController.swift
Labels: enhancement

#23 feat: 킥보드 찾기 화면에서 현위치로 가기 버튼 구현, 킥보드 대여/반납 모달 UI 구현
  Quick-Kick/SearchKickboard/View/RentKickboardModalView.swift
  Quick-Kick/SearchKickboard/View/SearchKickboardMapView.swift
  Quick-Kick/SearchKickboard/View/SearchKickboardView.swift
  Quick-Kick/SearchKickboard/View/SearchLocationBarView.swift
  Quick-Kick/ViewController.swift
Labels: enhancement

#24 feat: 킥보드 등록 모달뷰 구현 - Crois
  Quick-Kick/AddKickboard/AddKickboardView.swift
  Quick-Kick/AddKickboard/AddKickboardViewController.swift
  Quick-Kick/AddKickboard/ModalViewDelegate.swift
  Quick-Kick/RegistrationModalView/Controller/RegistrationModalViewController.swift
  Quick-Kick/RegistrationModalView/Model/RegistrationViewDelegate.swift
  Quick-Kick/RegistrationModalView/View/KickboardTypeButton.swift
  Quick-Kick/RegistrationModalView/View/RegistrationButton.swift
  Quick-Kick/RegistrationModalView/View/RegistrationTextField.swift
Labels: enhancement

#31 [DetailView] 마이 페이지 뷰/ 킥보드 디테일뷰 구현
  Quick-Kick/AddKickboard/ModalViewDelegate.swift
  Quick-Kick/MyKickboardDetailView/MyKickboardDetailView.swift
  Quick-Kick/MyKickboardDetailView/MyKickboardDetailViewController.swift
  Quick-Kick/MyKickboardDetailView/MyKickboardDetailViewItem.swift
  Quick-Kick/RegistrationModalView/Controller/RegistrationModalViewController.swift
  Quick-Kick/RegistrationModalView/View/KickboardTypeButton.swift
  Quick-Kick/RegistrationModalView/View/RegistrationTextField.swift
  Quick-Kick/ViewContorller/MyPageViewController.swift
Labels: enhancement

#34 feat: Userdefaults & Login
  Quick-Kick.xcodeproj/project.pbxproj
  Quick-Kick/AppDelegate.swift
  Quick-Kick/Extension/UITextField+Ext.swift
  Quick-Kick/Managers/UserDefaultsManager.swift
  Quick-Kick/View/LoginView.swift
  Quick-Kick/View/SignUpView.swift
  Quick-Kick/ViewContorller/LoginViewController.swift
  Quick-Kick/ViewContorller/SignUpViewController.swift
Labels: enhancement

#39 [Onboarding] 온보딩 페이지뷰 구현
  Quick-Kick/Assets.xcassets/onboadingImage_kickboard.imageset/Contents.json
  Quick-Kick/Assets.xcassets/onboadingImage_kickboard.imageset/NBC Design Icon.png
  Quick-Kick/Assets.xcassets/onboadingImage_safe.imageset/Contents.json
  Quick-Kick/Assets.xcassets/onboadingImage_safe.imageset/Group 39.png
  Quick-Kick/Base.lproj/LaunchScreen.storyboard
  Quick-Kick/OnboadingPage/OnboadingView/OnboardingPageView.swift
  Quick-Kick/OnboadingPage/OnboadingViewController/OnboardingPageViewController.swift
  Quick-Kick/OnboadingPage/OnboardingDataModel/OnboardingDataModel.swift
  Quick-Kick/OnboadingPage/OnboardingDataModel/OndoardingDelegate.swift
Labels: enhancement

#41 feat: 킥보드 대여/반납 모달 이벤트 구현
  Quick-Kick/AddKickboard/ModalViewDelegate.swift
  Quick-Kick/Assets.xcassets/myMapPicker.imageset/Contents.json
  Quick-Kick/Assets.xcassets/myMapPicker.imageset/myMapPicker.png
  Quick-Kick/SearchKickboard/Controller/SearchKickboardViewController.swift
  Quick-Kick/SearchKickboard/View/KickboardAnnotation.swift
  Quick-Kick/SearchKickboard/View/RentKickboardModalView.swift
  Quick-Kick/SearchKickboard/View/SearchKickboardMapView.swift
  Quick-Kick/SearchKickboard/View/SearchKickboardView.swift
  Quick-Kick/SearchKickboard/View/SearchLocationBarView.swift
Labels: enhancement

#53 [Logout]: 로그아웃 기능 구현
  Quick-Kick/ViewContorller/MyPageViewController.swift
Labels: enhancement

#55 feat: 지도 터치 시 모달 뷰 내려가도록 구현, 모달 반납버튼 구현
  Quick-Kick/AddKickboard/ModalViewDelegate.swift
  Quick-Kick/SearchKickboard/Controller/SearchKickboardViewController.swift
  Quick-Kick/SearchKickboard/View/RentKickboardModalView.swift
  Quick-Kick/SearchKickboard/View/SearchKickboardMapView.swift
Labels: enhancement

#63 [CoreData] 업데이트 기능 구현
  Quick-Kick/AddKickboard/ModalViewDelegate.swift
  Quick-Kick/Managers/CoreDataManager.swift
  Quick-Kick/MyKickboardDetailView/MyKickboardDetailView.swift
  Quick-Kick/MyKickboardDetailView/MyKickboardDetailViewController.swift
  Quick-Kick/RegistrationModalView/Controller/RegistrationModalViewController.swift
  Quick-Kick/RegistrationModalView/Model/RegistrationViewDelegate.swift
  Quick-Kick/RegistrationModalView/View/KickboardTypeButton.swift
  Quick-Kick/RegistrationModalView/View/RegistrationButton.swift
  Quick-Kick/RegistrationModalView/View/RegistrationTextField.swift
  Quick-Kick/ViewContorller/MyPageViewController.swift
Labels: refactoring

#68 bug: 킥보드 등록 후 킥보드 찾기 이동 시 등록 킥보드 보이지 않는 오류 해결
  Quick-Kick/SearchKickboard/Controller/SearchKickboardViewController.swift
Labels: bug

#70 feat: 킥보드 삭제 기능 추가
  Quick-Kick/AddKickboard/AddKickboardViewController.swift
  Quick-Kick/MyKickboardDetailView/MyKickboardDetailView.swift
  Quick-Kick/MyKickboardDetailView/MyKickboardDetailViewController.swift
  Quick-Kick/MyKickboardDetailView/MyKickboardDetailViewItem.swift
  Quick-Kick/OnboadingPage/OnboadingView/OnboardingPageView.swift
  Quick-Kick/OnboadingPage/OnboadingViewController/OnboardingPageViewController.swift
  Quick-Kick/SearchKickboard/Controller/SearchKickboardViewController.swift
  Quick-Kick/ViewContorller/MyPageViewController.swift
Labels: enhancement

#72 [fix] UI 버그 수정
  Quick-Kick/MyKickboardDetailView/MyKickboardDetailViewController.swift
  Quick-Kick/RegistrationModalView/Controller/RegistrationModalViewController.swift
  Quick-Kick/RegistrationModalView/Model/RegistrationViewDelegate.swift
  Quick-Kick/RegistrationModalView/View/KickboardTypeButton.swift
  Quick-Kick/SearchKickboard/Controller/SearchKickboardViewController.swift
Labels: bug
